https://carp-shop.herokuapp.com/boils

###

https://carp-shop.herokuapp.com/boils/1

###

https://carp-shop.herokuapp.com/boils/manufacturer/2

###

https://carp-shop.herokuapp.com/boils/search?text=Super

###



